"""marine_foundation"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql
revision = '298a26b067d1'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('selected_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_pfz', sa.String(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('marine_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marine_observations_forecast_time'), 'marine_observations', ['forecast_time'], unique=False)
    op.create_index(op.f('ix_marine_observations_parameter'), 'marine_observations', ['parameter'], unique=False)
    op.create_table('marine_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('valid_until > valid_from'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marine_zones_geometry', 'marine_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_marine_zones_type'), 'marine_zones', ['type'], unique=False)
    op.create_table('pfz_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('valid_until > valid_from'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pfz_zones_geometry', 'pfz_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_pfz_zones_valid_until'), 'pfz_zones', ['valid_until'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)

def downgrade():
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_pfz_zones_valid_until'), table_name='pfz_zones')
    op.drop_index('idx_pfz_zones_geometry', table_name='pfz_zones', postgresql_using='gist')
    op.drop_table('pfz_zones')
    op.drop_index(op.f('ix_marine_zones_type'), table_name='marine_zones')
    op.drop_index('idx_marine_zones_geometry', table_name='marine_zones', postgresql_using='gist')
    op.drop_table('marine_zones')
    op.drop_index(op.f('ix_marine_observations_parameter'), table_name='marine_observations')
    op.drop_index(op.f('ix_marine_observations_forecast_time'), table_name='marine_observations')
    op.drop_table('marine_observations')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###

